### PR TITLE
Make a way to extract properties from a module in a list

### PR DESCRIPTION
**Pull request by Lysxia**
Motivated by https://stackoverflow.com/questions/47953171/using-the-quickcheckall-function-in-tasty-quickcheck

### CODE REVIEW

**Comment by asr** [comment]
The above commit says that the type of `allProperties` is `[(String, Property)]` but if I defined

```haskell
foo :: [(String, Property)]
foo = allProperties
```

I got the error

```haskell
    • Couldn't match expected type ‘[(String, Property)]’
                  with actual type ‘Language.Haskell.TH.Syntax.Q
                                      Language.Haskell.TH.Syntax.Exp’
    • In the expression: allProperties
      In an equation for ‘foo’: foo = allProperties
```

**Comment by phadej** [comment]
@asr, `$allProperties` vs `allProperties`

**Comment by asr** [comment]
Oops! Thanks!

**Comment by asr** [comment]
@nick8325, this PR fix the problem pointed out in the OP. Thanks @Lysxia! Could you merge it and make a release, please?

Blocking https://github.com/agda/agda/issues/2861.

**Comment by asr** [comment]
@nick8325  , thanks for merging! Could you make a release, please?

**Comment by nick8325** [comment]
Will do in the next few days, as soon as I get some time!

**Comment by nick8325** [comment]
QuickCheck 2.11 is released now!

**Comment by asr** [comment]
Great! Thanks!

**Pull request merged**
