### PR TITLE
Test with more GHC versions on Travis-CI

### PR DESCRIPTION
**Pull request by emwap**
Update the Travis-CI configuration to use more GHC and cabal versions from the hvr-ghc ppa.
Also switch to the dockerized platform

### CODE REVIEW

**Comment by phadej** [comment]
@emwap `-j2` is crucial for newer GHC.
- with `-j2` in https://travis-ci.org/nick8325/quickcheck/builds/58753969 GHC 7.10 build took 4:29
- without in https://travis-ci.org/nick8325/quickcheck/builds/58755327 GHC 7.10 build took 15:48.

I'd make:
```yaml
matrix:
  include:
    - env: CABALVER=1.16 GHCVER=7.4.2 CABALJFLAG=""
      addons: {apt: {sources: [hvr-ghc], packages: [cabal-install-1.16,ghc-7.4.2]}}
    - env: CABALVER=1.18 GHCVER=7.6.3 CABALJFLAG=-j2
      addons: {apt: {sources: [hvr-ghc], packages: [cabal-install-1.18,ghc-7.6.3]}}
    - env: CABALVER=1.18 GHCVER=7.8.4 CABALJFLAG=-j2
      addons: {apt: {sources: [hvr-ghc], packages: [cabal-install-1.18,ghc-7.8.4,happy-1.19.4,alex-3.1.3]}}
    - env: CABALVER=1.22 GHCVER=7.10.1 CABALJFLAG=-j2

...
- cabal build $CABALJFLAG
```

Otherwise LGTM

**Comment by phadej** [comment]
Or actually the `multi-ghc-travis` solution is better: https://github.com/hvr/multi-ghc-travis#known-issues
```yaml
install:
# ...
  - travis_retry cabal update
  - sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config
# ...
```

**Comment by phadej** [comment]
This is obsolete?

**Comment by nick8325** [comment]
I think so!

**Pull request closed without merging**
