### PR TITLE
Negative & NonPositive

### PR DESCRIPTION
**Pull request by BebeSparkelSparkel**
Trying to keep from obfuscating my code by negating Positive.

### CODE REVIEW

**Comment by phadej** [comment]
We'd need `NonPositive` for completeness too.

**Comment by BebeSparkelSparkel** [comment]
@phadej I'm having problems building this. When I `cabal configure` it errors with `cabal: failed to parse output of 'ghc-pkg dump'`. What command should I use to build this?

**Comment by Lysxia** [comment]
`cabal new-build` should be the only thing to build.

**Comment by BebeSparkelSparkel** [comment]
@Lysxia Thanks. I needed to reinstall cabal

**Comment by nick8325** [comment]
Thanks! In the end I rewrote the patch to generate negative numbers directly, because negating the output of `Positive` wouldn't ever generate `minBound` for twos-complement integers.

**Comment by BebeSparkelSparkel** [comment]
I didn't even think of that. Appreciate your help getting that right

**Comment by nick8325** [comment]
I think that `Positive` had a similar bug in the past, which is why I spotted it :)

**Pull request merged**
