### PR TITLE
replace "Falsifiable" in error message into some better word

### PR DESCRIPTION
**Pull request by luochen1990**
I think use "Falsifiable" here is not very appropriate, since it emphasize the **inherent possibility** that a statement can be proven false. In our case, the proposition is already shown to be False, and we have found an obvious evidence about that, so I think "Falsism" could be better here.

> Falsifiability or refutability of a statement, hypothesis, or theory is the inherent possibility that it can be proven false. A statement is called falsifiable if it is possible to conceive of an observation or an argument which negates the statement in question.

> A falsism is a claim that is clearly and self-evidently wrong. A falsism is usually used merely as a reminder or as a rhetorical or literary device. An example is "pigs can fly." It is the opposite of truism.

### CODE REVIEW

**Comment by quasicomputational** [comment]
How about just 'Falsified'? 'Falsism' is a word I've literally never come across before today and I think most native speakers would be puzzled by it; it's got less than ten thousand Google hits, too.

**Comment by luochen1990** [comment]
@quasicomputational Thanks for your suggestion, I think the semantic here is "this proposition have been proved to be false obviously", and I'm not sure which word express this semantic naturally for native speakers. Is there any other comment or suggestion?   should I change it to "Falsified" or something else?

**Comment by Lysxia** [comment]
If I read the definition correctly, it's not a falsism if you need to prove it false, as is the case of QuickCheck properties, that look for counterexamples. Even my spell-checker doesn't know that word. "Falsified" sounds better.

**Comment by luochen1990** [comment]
@Lysxia Yes, if you look at the total property, it is not an falsism, but this word appears in the following code:
```
liftBool :: Bool -> Result
liftBool True = succeeded
liftBool False = failed { reason = "Falsifiable" }
liftBool False = failed { reason = "Falsism" }
```
here, "falsism" explains why we return `failed` when we get a `False`.

But if this word "falsism" is so rarely used, I think it will not be a good idea to use it here.  I will change it to "Falsified".

**Comment by nick8325** [comment]
"Falsified" sounds good to me. Thanks for the patch!

**Comment by tom-audm** [comment]
For what it's worth, I prefer "Falsifiable", as in "your proposition is falsifiable, and here's an example that proves it"

"Failed! Falsified" feels repetitive to me.

**Pull request merged**
