### PR TITLE
Provide Function instances for Const and Identity

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by eschnett** [comment]
Looking for guidance: Once this patch works for older versions of GHC, would it be welcome here in this package, or should it rather go to [`quickcheck-instances`](https://github.com/phadej/qc-instances) instead?

**Comment by phadej** [comment]
@eschnett use `Control.Applicative`. `Const` lives there on older GHC - no need to touch `quickcheck-instance` for it.

**Comment by Lysxia** [comment]
@eschnett Basically, it should be fine to add instances for types in packages that QuickCheck already depends on.

**Comment by eschnett** [comment]
The patch is ready to go.

**Comment by nick8325** [comment]
Thanks!

**Pull request merged**
