### PR TITLE
Update Gen.hs

### PR DESCRIPTION
**Pull request by amigalemming**
reference to new quickcheck-transformer package

### CODE REVIEW

**Comment by phadej** [comment]
I wonder what's the difference between `quickcheck-GenT` and `quickcheck-transformer`? (And why there is virtually the same package twice on Hackage?)

**Comment by amigalemming** [comment]
On Tue, 22 Jan 2019, Oleg Grenrus wrote:

> I wonder what's the difference between quickcheck-GenT and 
> quickcheck-transformer? (And why there is virtually the same package 
> twice on Hackage?)

As the description says: quickcheck-transformer is a fork of 
QuickCheck-GenT that does not need GHC extensions and works with GHC back 
to 7.0.4. The author of QuickCheck-GenT did not want maintain code for old 
GHC versions.

**Comment by phadej** [comment]
Is there a point to mention `QuickCheck-GenT` at all then?

**Comment by amigalemming** [comment]
On Tue, 22 Jan 2019, Oleg Grenrus wrote:

> Is there a point to mention QuickCheck-GenT at all then?

Not necessarily.

**Comment by phadej** [comment]
FWIW, http://packdeps.haskellers.com/reverse/QuickCheck-GenT has only one reverse dependency. `quickcheck-transformer` seems to have none (yet?)

**Comment by amigalemming** [comment]
On Tue, 22 Jan 2019, Oleg Grenrus wrote:

> FWIW, http://packdeps.haskellers.com/reverse/QuickCheck-GenT has only one reverse dependency.
> quickcheck-transformer seems to have none (yet?)

quickcheck-transformer is newer and thus has fewer users - but there is 
one:
   https://hackage.haskell.org/package/lapack-0.2.1/lapack.cabal

(only the test-suite depends on it)

**Comment by nick8325** [comment]
I don't know if it's best to refer to both packages or only to `quickcheck-transformers`, but that's no reason to not merge the patch :)

**Pull request merged**
